# Configuration for https://goreleaser.com/
project_name: authenticator

builds:
  - binary: aws-iam-authenticator
    main: ./cmd/aws-iam-authenticator/
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"

dockers:
  - binary: aws-iam-authenticator
    dockerfile: Dockerfile.scratch
    image_templates:
     - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:{{ .Tag }}-scratch"
     - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:{{ .Tag }}"
  - binary: aws-iam-authenticator
    dockerfile: Dockerfile.alpine-3.6
    image_templates:
     - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:{{ .Tag }}-alpine-3.6"
  - binary: aws-iam-authenticator
    dockerfile: Dockerfile.alpine-3.7
    image_templates:
     - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:{{ .Tag }}-alpine-3.7"
     - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:{{ .Tag }}-alpine"
  - binary: aws-iam-authenticator
    dockerfile: Dockerfile.debian-jessie
    image_templates:
     - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:{{ .Tag }}-debian-jessie"
  - binary: aws-iam-authenticator
    dockerfile: Dockerfile.debian-stretch
    image_templates:
     - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:{{ .Tag }}-debian-stretch"
     - "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:{{ .Tag }}-debian"

snapshot:
  name_template: "git-{{.ShortCommit}}"

archive:
  format: binary

release:
  github:
    owner: kubernetes-sigs
    name: aws-iam-authenticator
  draft: true
  prerelease: false
  name_template: "v{{.Version}}"
